classes: {
  rectangle: {
    shape: rectangle

    style: {
      fill: "#f9f9f9"

      stroke: "#333"

      "stroke-width": 2

      "border-radius": 4
    }
  }

  CoreDependencyArrow: {
    style: {
      stroke: "#00f"

      "stroke-width": 2
    }
  }

  DomainDependencyArrow: {
    style: {
      stroke: "#f00"

      "stroke-width": 2
    }
  }

  DefaultArrow: {
    style: {
      stroke: "#555"

      "stroke-width": 2
    }
  }

  CoreLayerStyle: {
    shape: rectangle

    style: {
      fill: "#d1e7dd"

      stroke: "#0f5132"

      "stroke-width": 2

      "border-radius": 6
    }
  }

  DataLayerStyle: {
    shape: rectangle

    style: {
      fill: "#cff4fc"

      stroke: "#055160"

      "stroke-width": 2

      "border-radius": 6
    }
  }

  DomainLayerStyle: {
    shape: rectangle

    style: {
      fill: "#f8d7da"

      stroke: "#842029"

      "stroke-width": 2

      "border-radius": 6
    }
  }

  ApplicationLayerStyle: {
    shape: rectangle

    style: {
      fill: "#fff3cd"

      stroke: "#664d03"

      "stroke-width": 2

      "border-radius": 6
    }
  }

  FeatureLayerStyle: {
    shape: rectangle

    style: {
      fill: "#d0ebff"

      stroke: "#084298"

      "stroke-width": 2

      "border-radius": 6
    }
  }

  SharedLayerStyle: {
    shape: rectangle

    style: {
      fill: "#e2e3e5"

      stroke: "#41464b"

      "stroke-width": 2

      "border-radius": 6
    }
  }
}

